### PR TITLE
Added a database-based multi-user feature

### LINKED ISSUE #11: Implement multi-user support
Currently, the password manager is designed for a single user. Implement multi-user support, where multiple users can create, store, and manage their passwords independently within the same application.

### LINKED ISSUE #12: Add a graphical user interface (GUI)
Implement a simple GUI for the password manager using a library like Tkinter. The GUI should allow users to interact with the manager visually instead of through the CLI.

### PR DESCRIPTION
**Pull request by Entity069**
### Related Issue  
Closes #11 

### Type of Change
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [x] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Implemented a multi-user system an SQLite database with SQLAlchemy as a backend

### Implementation Details  
- Implemented a SQLAlchemy backed SQLite database based multi-user system
- Updated README.md
- Three tables in the database: Users, Keys, Passwords
- Database Structure:
Screenshot_20241218_035900
- If a user enters a password for a site more than once, it is stored as a twice entry. However only the latest entered password is returned.

### Demo

https://github.com/user-attachments/assets/8fa94564-a11a-40dd-9135-66cb9733ae38

### CODE REVIEW

**Comment by Entity069** [comment]
@Hardik-2311 conflicts have been resolved. Pls review the PR

**Comment by Hardik-2311** [comment]
@fillingtothemomo  lgtm

**Comment by Hardik-2311** [comment]
@Entity069  Could you kindly verify if you have registered for MergeFest and provide your credentials?

Thank you!

**Comment by Entity069** [comment]
@Hardik-2311 i actually didn't registered but i have sent my credentials to one of the seniors (late registration)

**Comment by Hardik-2311** [comment]
@Entity069 his/her name?

**Comment by Entity069** [comment]
@Hardik-2311 dont know his name, he goes by KiRiTo13 on discord

**Pull request merged**
